### PR TITLE
Fix compile errors with mongo-c-driver v0.7.1

### PR DESCRIPTION
**Pull request by eagleas**
Ubuntu 12.04, x86_64

### CODE REVIEW

**Comment by Reggino** [comment]
Thanks, this helped me a lot!

**Comment by philostler** [comment]
Same here, helped me loads, big thanks! Why is this pull not been taken into master!?!?

This project looks stale in the original repo but there's still a great need for GridFS support in Nginx out there. Full respect to the original authors but if they don't have the time to handle the ongoing maintenance of this plugin then it should be handed on to someone else so it progress (like getting HTTP range support added).

**Comment by mdirolf** [comment]
@philostler you hit the nail on the head, I just don't have the time needed to devote to this project. I'd be happy to hand the reins over to somebody who does, just haven't really had any offers come my way.

**Comment by philostler** [comment]
I'm love to take it over for you but I've hardly written a line of C in 10 years :weary:

**Pull request merged**
